version: '3.1'
services:

  site:
    build: ./
    ports:
    - "5000:5000"
    restart: always


  ngnix:
    build: ./ngnix
    ports:
    - "80:80"
    links:
    - site:site
    restart: always


